env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 80
    lines: 24
  padding:
    x: 2
    y: 2

scrolling:
  history: 10000
  multiplier: 3
  auto_scroll: false

font:
  normal:
    family: SF Mono
    style: Semibold
  size: 16

background_opacity: 1

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }


cursor:
  style: Block

tabspaces: 2

# Colors (iTerm 2 default theme)
colors:
  # Default colors
  primary:
    background: '0x101421'
    foreground: '0xfffbf6'

  # Normal colors
  normal:
    black:   '0x2e2e2e'
    red:     '0xeb4129'
    green:   '0xabe047'
    yellow:  '0xf6c744'
    blue:    '0x47a0f3'
    magenta: '0x7b5cb0'
    cyan:    '0x64dbed'
    white:   '0xe5e9f0'

  # Bright colors
  bright:
    black:   '0x565656'
    red:     '0xec5357'
    green:   '0xc0e17d'
    yellow:  '0xf9da6a'
    blue:    '0x49a4f8'
    magenta: '0xa47de9'
    cyan:    '0x99faf2'
    white:   '0xffffff'
